import img1 from "../assets/inspiration/inspiration-001.png";
import img2 from "../assets/inspiration/inspiration-002.png";
import img3 from "../assets/inspiration/inspiration-003.png";
import img4 from "../assets/inspiration/inspiration-004.png";
import img5 from "../assets/inspiration/inspiration-005.png";
import img6 from "../assets/inspiration/inspiration-006.png";
import img7 from "../assets/inspiration/inspiration-007.png";
import img8 from "../assets/inspiration/inspiration-008.png";

//restaurant
import restaurant1 from "../assets/placetostay/play-to-stay-001.png";
import restaurant2 from "../assets/placetostay/play-to-stay-002.png";
import restaurant3 from "../assets/placetostay/play-to-stay-003.png";
import restaurant4 from "../assets/placetostay/play-to-stay-004.png";
import restaurant5 from "../assets/placetostay/play-to-stay-005.png";
import restaurant6 from "../assets/placetostay/play-to-stay-006.png";
import restaurant7 from "../assets/placetostay/play-to-stay-007.png";
import restaurant8 from "../assets/placetostay/play-to-stay-008.png";
import restaurant9 from "../assets/placetostay/play-to-stay-009.png";
import restaurant10 from "../assets/placetostay/play-to-stay-010.png";
import restaurant11 from "../assets/placetostay/play-to-stay-011.png";
import restaurant12 from "../assets/placetostay/play-to-stay-012.png";
import restaurant13 from "../assets/placetostay/play-to-stay-013.png";
import restaurant14 from "../assets/placetostay/play-to-stay-014.png";
import restaurant15 from "../assets/placetostay/play-to-stay-015.png";
import restaurant16 from "../assets/placetostay/play-to-stay-016.png";

//Cottage
import cottage1 from "../assets/placetostay/play-to-stay-001.png";
import cottage2 from "../assets/placetostay/play-to-stay-002.png";
import cottage3 from "../assets/placetostay/play-to-stay-003.png";
import cottage4 from "../assets/placetostay/play-to-stay-004.png";
import cottage5 from "../assets/placetostay/play-to-stay-005.png";
import cottage6 from "../assets/placetostay/play-to-stay-006.png";
import cottage7 from "../assets/placetostay/play-to-stay-007.png";
import cottage8 from "../assets/placetostay/play-to-stay-008.png";
import cottage9 from "../assets/placetostay/play-to-stay-009.png";
import cottage10 from "../assets/placetostay/play-to-stay-010.png";
import cottage11 from "../assets/placetostay/play-to-stay-011.png";
import cottage12 from "../assets/placetostay/play-to-stay-012.png";
import cottage13 from "../assets/placetostay/play-to-stay-013.png";
import cottage14 from "../assets/placetostay/play-to-stay-014.png";
import cottage15 from "../assets/placetostay/play-to-stay-015.png";
import cottage16 from "../assets/placetostay/play-to-stay-016.png";

export const inspiration = [
  {
    id: 1,
    img: img1,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
  },
  {
    id: 2,
    img: img2,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
  },
  {
    id: 3,
    img: img3,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
  },
  {
    id: 4,
    img: img4,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
  },
  {
    id: 5,
    img: img5,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
  },
  {
    id: 6,
    img: img6,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
  },
  {
    id: 7,
    img: img7,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
  },
  {
    id: 8,
    img: img8,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
  },
];

export const playToStay = [
  {
    id: 1,
    img: restaurant1,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "restaurant",
  },
  {
    id: 2,
    img: restaurant2,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "restaurant",
  },
  {
    id: 3,
    img: restaurant3,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "restaurant",
  },
  {
    id: 4,
    img: restaurant4,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "restaurant",
  },
  {
    id: 5,
    img: restaurant5,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "restaurant",
  },
  {
    id: 6,
    img: restaurant6,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "restaurant",
  },
  {
    id: 7,
    img: restaurant7,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "restaurant",
  },
  {
    id: 8,
    img: restaurant8,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "restaurant",
  },
  {
    id: 9,
    img: restaurant9,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "restaurant",
  },
  {
    id: 10,
    img: restaurant10,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "restaurant",
  },
  {
    id: 11,
    img: restaurant11,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "restaurant",
  },
  {
    id: 12,
    img: restaurant12,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "restaurant",
  },
  {
    id: 13,
    img: restaurant13,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "restaurant",
  },
  {
    id: 14,
    img: restaurant14,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "restaurant",
  },
  {
    id: 15,
    img: restaurant15,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "restaurant",
  },
  {
    id: 16,
    img: restaurant16,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "restaurant",
  },
  {
    id: 17,
    img: "https://www.nicepng.com/png/detail/89-898869_send-house-building-png-3d.png",
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "cottage",
  },
  {
    id: 18,
    img: "https://www.pngmart.com/files/21/3D-Building-House-PNG-HD.png",
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "cottage",
  },
  {
    id: 19,
    img: "https://iili.io/yM9Mlt.md.png",
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "cottage",
  },
  {
    id: 20,
    img: "https://www.renderhub.com/virtual3d/cottage-house-4/cottage-house-4-01.jpg",
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "cottage",
  },
  {
    id: 21,
    img: "https://www.renderhub.com/virtual3d/cottage-house-1/cottage-house-1-03.jpg",
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "cottage",
  },
  {
    id: 22,
    img: cottage6,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "cottage",
  },
  {
    id: 23,
    img: cottage7,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "cottage",
  },
  {
    id: 24,
    img: cottage8,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "cottage",
  },
  {
    id: 25,
    img: cottage9,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "cottage",
  },
  {
    id: 26,
    img: cottage10,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "cottage",
  },
  {
    id: 27,
    img: "https://p.turbosquid.com/ts-thumb/dT/bL4GV2/Rr1N7DKU/fc_01/jpg/1473025379/600x600/fit_q87/054516cc83c899f05d5d881e5b23e5b9b12d9bf2/fc_01.jpg",
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "castle",
  },
  {
    id: 28,
    img: "https://blenderartists.org/uploads/default/original/4X/6/2/7/6277d8f3a20b1db366c70fd2f318aba61f61d184.jpg",
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "castle",
  },
  {
    id: 29,
    img: "https://p.turbosquid.com/ts-thumb/n5/wRaIuE/8GZBgurn/2/jpg/1332516576/600x600/fit_q87/2af42621300ad7ff84290bc9123ce5a638c7ef14/2.jpg",
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "castle",
  },
  {
    id: 30,
    img: "https://files.cults3d.com/uploaders/17022466/illustration-file/84c634ca-7b26-44ee-b911-4c3597dd475a/20210227_115450.jpg",
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "castle",
  },
  {
    id: 31,
    img: "https://www.happypuzzle.co.uk/uploads/productimages/large/9115_1613656561_medievil2.jpg",
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "castle",
  },
  {
    id: 32,
    img: cottage6,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "castle",
  },
  {
    id: 33,
    img: cottage7,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "castle",
  },
  {
    id: 34,
    img: cottage8,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "castle",
  },
  {
    id: 35,
    img: cottage9,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "castle",
  },
  {
    id: 36,
    img: cottage10,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "castle",
  },
  {
    id: 37,
    img: "https://i.pinimg.com/originals/d5/ed/88/d5ed886540d8fb079db81a6c19e74889.jpg",
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "fantasticCity",
  },
  {
    id: 38,
    img: "https://i.pinimg.com/736x/23/76/4d/23764d7a7ef9076571efa067ab43d587.jpg",
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "fantasticCity",
  },
  {
    id: 39,
    img: "https://free4kwallpapers.com/uploads/originals/2015/10/03/3d-ice-age-future-fantasy-city.jpg",
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "fantasticCity",
  },
  {
    id: 40,
    img: "https://w0.peakpx.com/wallpaper/1005/555/HD-wallpaper-ice-age-fantasy-3d-city-future-ice-abstract.jpg",
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "fantasticCity",
  },
  {
    id: 41,
    img: "https://cdnb.artstation.com/p/assets/images/images/005/964/781/large/julien-tonsuso-s11.jpg?1495040627",
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "fantasticCity",
  },
  {
    id: 42,
    img: cottage6,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "fantasticCity",
  },
  {
    id: 43,
    img: cottage7,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "fantasticCity",
  },
  {
    id: 44,
    img: cottage8,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "fantasticCity",
  },
  {
    id: 45,
    img: cottage9,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "fantasticCity",
  },
  {
    id: 46,
    img: cottage10,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "fantasticCity",
  },
  {
    id: 47,
    img: "https://m.media-amazon.com/images/I/51w2o-kNBVL.jpg",
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "beach",
  },
  {
    id: 48,
    img: "https://img.freepik.com/premium-photo/beauty-summer-beach-surfboard-sand-palm-tree-background-animation-3d-rendering_75775-777.jpg?w=2000",
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "beach",
  },
  {
    id: 49,
    img: "https://cdna.artstation.com/p/assets/images/images/038/841/864/large/zafra-playacartoondef.jpg?1624233172",
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "beach",
  },
  {
    id: 50,
    img: "https://i.pinimg.com/originals/24/52/6f/24526fe454cd1aa55f3b96de743d4a80.png",
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "beach",
  },
  {
    id: 51,
    img: "https://cdn.dribbble.com/users/269899/screenshots/10154533/shot-cropped-1581944796828.png?compress=1&resize=400x300&vertical=top",
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "beach",
  },
  {
    id: 52,
    img: cottage6,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "beach",
  },
  {
    id: 53,
    img: cottage7,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "beach",
  },
  {
    id: 54,
    img: cottage8,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "beach",
  },
  {
    id: 55,
    img: cottage9,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "beach",
  },
  {
    id: 56,
    img: cottage10,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "beach",
  },
  {
    id: 57,
    img: "https://media.sketchfab.com/models/8610b8b1b26443ba861b669cebfa1d5f/thumbnails/46b52244e5e449b5aa4b190dacdbebdb/1f3bea7646944aef83a561ed10ea7c83.jpeg",
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "carbins",
  },
  {
    id: 58,
    img: "https://media.sketchfab.com/models/96e27e65346945869366d03dd5cf5b11/thumbnails/82a4af1b52c54f90b2d39fe5cbf96945/f08b3b4c33fe49f18a33e5013a5db7e1.jpeg",
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "carbins",
  },
  {
    id: 59,
    img: "https://media.sketchfab.com/models/d3fc5ddb339a4a8a81bc42ced82b5b0c/thumbnails/240ca80d6fb5451ea0a076aad7b1c2f2/41a8cf2984784212b9c423641c50dd08.jpeg",
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "carbins",
  },
  {
    id: 60,
    img: "https://p.turbosquid.com/ts-thumb/zX/TBmqU8/XiEHEVyO/log_cabin_contextsig_0000/jpg/1500927690/600x600/fit_q87/c409050c17465fb42a03cb5212c51d2db04df252/log_cabin_contextsig_0000.jpg",
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "carbins",
  },
  {
    id: 61,
    img: "https://cdn.dribbble.com/users/269899/screenshots/10154533/shot-cropped-1581944796828.png?compress=1&resize=400x300&vertical=top",
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "carbins",
  },
  {
    id: 62,
    img: cottage6,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "carbins",
  },
  {
    id: 63,
    img: cottage7,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "carbins",
  },
  {
    id: 64,
    img: cottage8,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "carbins",
  },
  {
    id: 65,
    img: cottage9,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "carbins",
  },
  {
    id: 66,
    img: cottage10,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "carbins",
  },
  {
    id: 67,
    img: "https://boomersdaily.files.wordpress.com/2020/06/io-house.jpg?w=1200",
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "offgrid",
  },
  {
    id: 68,
    img: "https://s3.amazonaws.com/electronichousesite/wp-content/uploads/2017/03/31105035/PassivDom-prototype-1.jpg",
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "offgrid",
  },
  {
    id: 69,
    img: "https://unacasa.us/wp-content/uploads/2021/01/IOHOUSE-6.jpg",
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "offgrid",
  },
  {
    id: 70,
    img: "https://www.som.com/wp-content/uploads/2021/07/amie_summer_680x510_som.jpg",
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "offgrid",
  },
  {
    id: 71,
    img: "https://inhabitat.com/wp-content/blogs.dir/1/files/2017/04/3D-printed-modular-homes-by-PassivDom-9.jpg",
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "offgrid",
  },
  {
    id: 72,
    img: cottage6,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "offgrid",
  },
  {
    id: 73,
    img: cottage7,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "offgrid",
  },
  {
    id: 74,
    img: cottage8,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "offgrid",
  },
  {
    id: 75,
    img: cottage9,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "offgrid",
  },
  {
    id: 76,
    img: cottage10,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "offgrid",
  },
  {
    id: 77,
    img: "https://img.freepik.com/premium-vector/rural-3d-farm-isometric-template-with-garden-field-farmer-house-greenhouse-game-app-illustration_88272-1441.jpg?w=2000",
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "farm",
  },
  {
    id: 78,
    img: "https://img.freepik.com/premium-vector/rural-3d-farm-isometric-template-with-mill-garden-trees-agricultural-vehicles-farmer-house-greenhouse-game-app-illustration_88272-1458.jpg?w=2000",
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "farm",
  },
  {
    id: 79,
    img: "https://wallpaperaccess.com/full/2131327.jpg",
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "farm",
  },
  {
    id: 80,
    img: "https://buildingkentucky.com/wp-content/uploads/2020/04/horsefarm-1030x579.jpg",
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "farm",
  },
  {
    id: 81,
    img: "https://faithbridge.org/wp-content/uploads/2022/01/Kentucky.jpg",
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "farm",
  },
  {
    id: 82,
    img: cottage6,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "farm",
  },
  {
    id: 83,
    img: cottage7,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "farm",
  },
  {
    id: 84,
    img: cottage8,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "farm",
  },
  {
    id: 85,
    img: cottage9,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "farm",
  },
  {
    id: 86,
    img: cottage10,
    title: "Desert king",
    duration: "1MBT per night",
    distance: "2345km away",
    availability: "available for 2weeks stay",
    category: "farm",
  },
];